### PR TITLE
Reservation

### PR DESCRIPTION
**Pull request by Quindows**

### CODE REVIEW

**Review by ReyhanGe — APPROVED** [review]
De code is goed geschreven en begrijpelijk.

**Comment by Quindows** [comment]
fixed styling requested by daniël

**Review by dphoeng — CHANGES_REQUESTED** [review]
Fixed issues together regarding finding an empty table and error message when no table is available
Tested, waiting for openingtimeid fix to be included in the query

**Review by dphoeng — APPROVED** [review]
Looking good now

**Pull request merged**
